version: '3.9'

services:
  db4:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db4
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app

  web4:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:8001"
    depends_on:
      - db4
      - redis
    networks:
      - app
    restart: always

  celery_worker:
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db4
      - redis
    networks:
      - app
    restart: always

  celery_beat:
    build: .
    command: celery -A core beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db4
      - redis
    networks:
      - app
    restart: always

networks:
  app:

volumes:
  pgdata:















# version: '3.9'

# services:
#   web4:
#     build: .
#     container_name: drf4_web
#     command: python manage.py runserver 0.0.0.0:8001
#     volumes:
#       - .:/app
#     ports:
#       - "8001:8001"
#     env_file:
#       - .env
#     depends_on:
#       - db4

#   db4:
#     image: postgres:16
#     container_name: postgres_drf4_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}

# volumes:
#   postgres_data:
